# Generated by Django 3.0.7 on 2020-07-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/usericon.png', null=True, upload_to='images/user-picture'),
        ),
    ]
