# Generated by Django 3.0 on 2020-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200702_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/usericon.png', null=True, upload_to='user-pic'),
        ),
    ]
