# Generated by Django 3.0 on 2020-12-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201201_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='awards',
            field=models.IntegerField(null=True),
        ),
    ]
