# Generated by Django 3.0 on 2020-12-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201201_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='awards',
            field=models.IntegerField(default=0),
        ),
    ]
