# Generated by Django 3.0 on 2020-12-02 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_client_count_cta_feature_hero_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='about',
            name='happy_clients',
        ),
        migrations.RemoveField(
            model_name='about',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='about',
            name='years',
        ),
        migrations.AddField(
            model_name='count',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='count',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='count',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
