# Generated by Django 3.0 on 2020-12-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20201202_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
