# Generated by Django 3.0 on 2020-12-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='Portfolio test blah blah blah my portfolio test'),
        ),
    ]
