# Generated by Django 3.0 on 2020-12-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_newsletter_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='desciption',
            new_name='description',
        ),
    ]
